
def one():
    print("-----------------------------------------------------------")
    print("---> Python print() function prints the message to \nthe screen or any other standard output device.")
    print("----------------------------------------------------------")
    print("----------------------------------------------------")
    print("|            These are the subtopics of            |")
    print("|                  Print Statement                 |")
    print("|                                                  |")
    print("|              a. Basic printing                   |")
    print("|              b. Printing with variable           |")
    print("|              c. Printing Input                   |")
    print("----------------------------------------------------")


def one_a():
    print("---------------------------------------------------------")
    print("---> To print a fixed input, place the value directly \ninside the parentheses of the print()")
    print("---------------------------------------------------------")
    print("Input:")
    print('1. \tprint("You did well today")')
    print('2. \tprint(99)')
    print("   ")
    print("Output: ")
    print("1. \tYou did well today")
    print("2. \t99")
    print("---------------------------------------------------------")

def one_b():
    print("---------------------------------------------------------")
    print("---> To print with variable, place the variable name \ndirectly inside the print() function's parentheses.")
    print("---------------------------------------------------------")
    print("Input:")
    print('1. x = "Shaira Joy A. Calapit"')
    print(' \tprint(x)')
    print("                                  ")
    print('2. \tname = Lalisa Manoban") \nprint("Hello", name, "Welcome to the Matrix")')
    print("   ")
    print("Output: ")
    print("1. \tShaira Joy A. Calapit")
    print("                                  ")
    print("2. \tHello Lalisa Manoban Welcome to the Matrix")
    print("---------------------------------------------------------")

def one_c():
    print("---------------------------------------------------------")
    print("---> Printing with user input in Python means using \ninput() in variable to get data from the user and then using \nprint() to display that data, making the program interactive.")
    print("---------------------------------------------------------")
    print("Input:")
    print("1. name = input('What's your name? --> ') ") 
    print('   print("Hi", name)')
    print("\n name --> Shaira")
    print("                                  ")
    print("Output: ")
    print("1. What's your name? --> ")
    print("   Hi Shaira")
    print("---------------------------------------------------------")


def two():
    print("-----------------------------------------------------------")
    print("---> Variables are used to store data that can be referenced and \nmanipulated during program execution. A variable is essentially \na name that is assigned to a value.")
    print("----------------------------------------------------------")
    print("----------------------------------------------------")
    print("|            These are the subtopics of            |")
    print("|                  Variables                       |")
    print("|                                                  |")
    print("|              a. Basic Creation                   |")
    print("|              b. Casting                          |")
    print("|              c. Getting the Type                 |")
    print("|              d. Case-Sensitive                   |")
    print("----------------------------------------------------")

def two_a():
    print("---------------------------------------------------------")
    print("---> A variable is created the moment you first assign a value to it.")
    print("---------------------------------------------------------")
    print("Input:")
    print('1. \tx = "How are you? ')
    print('\tprint(x)')
    print('2. \n\ty = 2')
    print('2. \tprint(y)')
    print("   ")
    print("Output: ")
    print("1. \tHow are you? ")
    print("2. \t2")
    print("---------------------------------------------------------")

def two_b():
    print("---------------------------------------------------------")
    print("---> If you want to specify the data type of a variable, this can be done with casting.")
    print("\nMAIN DATA TYPES OF VARIABLE")
    print("str - string is a sequence of characters represented by either single or double quotes.\nint - holds signed integers of non-limited length.\nfloat - holds floating decimal points and it's accurate up to 15 decimal places.")
    print("---------------------------------------------------------")
    print("Input:")
    print("1. \tx = str(3) ")
    print('\ty = int(3)')
    print('\tz = float(3)')
    print('\tprint(x)')
    print('\tprint(y)')
    print('\tprint(z)')

    print("Output: ")
    print("#x became'3'\n#y became 3\n#z became 3.0")
    print("\n3\n3\n3.0")
    print("---------------------------------------------------------")

def two_c():
    print("---------------------------------------------------------")
    print("---> You can get the data type of a variable with the type() function..")
    print("---------------------------------------------------------")
    print("Input:")
    print('1. \tx = 3')
    print('\tprint(type(x))')

    print('2. \n\tanything = eval(input("Input anything : "))')
    print('\tprint("The type of data that you input is (type(anything)) \n anything --> 4.8')
    print("   ")
    print("Output: ")
    print("1. \t<class 'int'>")
    print("2. \t<class 'float'>")
    print("---------------------------------------------------------")

def two_d():
    print("---------------------------------------------------------")
    print("---> A case-sensitive variable means that variable names \ndistinguish between uppercase and lowercase letters, so ab, aB, and AB \nare treated as three different identifiers.")
    print("---------------------------------------------------------")
    print("Input:")
    print('1. \n\task = "How old are you?" ')
    print('\tASK = 4 ')
    print('\tprint(ask)')
    print('\tprint(ASK)')
    print('2. \n\tA = "shaira"')
    print('\ta = "joy"')
    print('\tprint(a)')
    print('\tprint(A)')
    print("   ")
    print("Output: ")
    print("1. \tHow old are you? ")
    print("    ")
    print("2. \tjoy \n\tshaira")
    print("---------------------------------------------------------")

def three():
    print("-----------------------------------------------------------")
    print("---> Operators in Python are special symbols or keywords\n used to perform operations on values and variables, \nsuch as arithmetic, comparison, logical, and assignment.")
    print("----------------------------------------------------------")
    print("----------------------------------------------------")
    print("|            These are the subtopics of            |")
    print("|                  Operators                       |")
    print("|                                                  |")
    print("|              a. Arithmetic                       |")
    print("|              b. Comparison                       |")
    print("|              c. Logical                          |")
    print("|              d. Assignmnent                      |")
    print("----------------------------------------------------")

def three_a():
    print("---------------------------------------------------------")
    print("---> Arithmetic operators are used with numeric values \nto perform common mathematical operations.")
    print("\nTYPES OF OPERATORS\n")
    print("+  Addition       : adds values        -> x + y")
    print("-  Subtraction    : subtracts values   -> x - y")
    print("*  Multiplication : multiplies values  -> x * y")
    print("/  Division       : divides values     -> x / y")
    print("%  Modulus        : remainder          -> x % y")
    print("** Exponentiation : power              -> x ** y")
    print("// Floor division : quotient (floor)   -> x // y")
    print("---------------------------------------------------------")
    x = 5
    y = 3
    print("1. Addition: ")
    print("Input:")
    print("\tx = 5\n\ty = 3")
    print("\tprint(x + y)")
    print("Output:")
    print("\t",x + y)
    print("---------------------------------------------------------")
    print("    ")
    print("2. Subtraction: ")
    print("Input:")
    print("\tx = 5\n\ty = 3")
    print("\tprint(x - y)")
    print("Output:")
    print("\t",x - y)
    print("---------------------------------------------------------")
    print("    ")
    print("3. Multiplication: ")
    print("Input:")
    print("\tx = 5\n\ty = 3")
    print("\tprint(x * y)")
    print("Output:")
    print("\t",x * y)
    print("---------------------------------------------------------")
    print("    ")
    print("4. Division: ")
    print("Input:")
    print("\tx = 5\n\ty = 3")
    print("\tprint(x / y)")
    print("Output:")
    print("\t",x / y)
    print("---------------------------------------------------------")
    print("    ")
    print("5. Modulus: ")
    print("Input:")
    print("\tx = 5\n\ty = 3")
    print("\tprint(x % y)")
    print("Output:")
    print("\t",x % y)
    print("---------------------------------------------------------")
    print("    ")
    print("6. Exponentiation: ")
    print("Input:")
    print("\tx = 5\n\ty = 3")
    print("\tprint(x ** y)")
    print("Output:")
    print("\t",x ** y)
    print("---------------------------------------------------------")
    print("    ")
    print("7. Floor Division: ")
    print("Input:")
    print("\tx = 5\n\ty = 3")
    print("\tprint(x // y)")
    print("Output:")
    print("\t",x // y)
    print("---------------------------------------------------------")

def three_b():
    print("---------------------------------------------------------")
    print("---> Comparison operators are used to compare two values \nand return True or False.")
    print("\nTYPES OF COMPARISON OPERATORS\n")
    print("==  Equal to            : returns True if values are equal        -> x == y")
    print("!=  Not equal to        : returns True if values are not equal    -> x != y")
    print(">   Greater than        : returns True if left is greater         -> x > y")
    print("<   Less than           : returns True if left is smaller         -> x < y")
    print(">=  Greater or equal    : returns True if left >= right           -> x >= y")
    print("<=  Less or equal       : returns True if left <= right           -> x <= y")
    print("---------------------------------------------------------")

def three_b():
    print("---------------------------------------------------------")
    print("---> Comparison operators are used to compare two values \nand return True or False.")
    print("\nTYPES OF COMPARISON OPERATORS\n")
    print("==  Equal to            : returns True if values are equal        -> x == y")
    print("!=  Not equal to        : returns True if values are not equal    -> x != y")
    print(">   Greater than        : returns True if left is greater         -> x > y")
    print("<   Less than           : returns True if left is smaller         -> x < y")
    print(">=  Greater or equal    : returns True if left >= right           -> x >= y")
    print("<=  Less or equal       : returns True if left <= right           -> x <= y")
    print("---------------------------------------------------------")

    s = "shai"
    t = "shai"
    print("1. Equal to (==): ")
    print("Input:")
    print(f'\ts = {s}\n\tt = {t}')
    print("\tprint(s == t)")
    print("Output:")
    print("\t", s == t)
    print("---------------------------------------------------------")
    print("    ")
    x = "one"
    y = "one"
    print("2. Not equal to (!=): ")
    print("Input:")
    print(f"\tx = {x}\n\ty = {y}")
    print("\tprint(x != y)")
    print("Output:")
    print("\t", x != y)
    print("---------------------------------------------------------")
    print("    ")
    sum1 = 1
    sum2 = 2

    print("3. Greater than (>): ")
    print("Input:")
    print(f"\tsum1 = {sum1}\n\tsum2 = {sum2}")
    print("\tprint(sum1 > sum2)")
    print("Output:")
    print("\t", sum1 > sum2)
    print("---------------------------------------------------------")
    print("    ")
    print("4. Less than (<): ")
    print("Input:")
    print(f"\tsum1 = {sum1}\n\tsum2 = {sum2}")
    print("\tprint(sum1 < sum2)")
    print("Output:")
    print("\t", sum1 < sum2)
    print("---------------------------------------------------------")
    print("    ")
    ex1 = 3
    ex2 = 3
    print("5. Greater or equal (>=): ")
    print("Input:")
    print(f"\tsum1 = {ex1}\n\tsum2 = {ex2}")
    print("\tprint(ex1 >= ex2)")
    print("Output:")
    print("\t", ex1 >= ex2)
    print("---------------------------------------------------------")
    print("    ")
    ex1 = 44
    ex2 = 45
    print("6. Less or equal (<=): ")
    print("Input:")
    print(f"\tex1 = {ex1}\n\tex2 = {ex2}")
    print("\tprint(ex1 <= ex2)")
    print("Output:")
    print("\t", ex1 <= ex2)
    print("---------------------------------------------------------")


def three_c():
    print("---------------------------------------------------------")
    print("---> Logical operators are used to combine conditional statements")
    print("\nTYPES OF LOGICAL OPERATORS\n")
    print("  and       : returns True if both statements are true        -> x and y")
    print("  or        : returns True if one of the statements is true   -> x or y")
    print("  not       : reverse the result                              -> not(x and y)")
    print("---------------------------------------------------------")

    name1 = "SHAI"
    name2 = "SHAI"

    print("1. and : \n")
    print("Input:")
    print(f'\tname1 = "{name1}"\n\tname2 = "{name2}"')
    print("\tprint((name1 == 'SHAI') and (name2 == 'SHAI'))")
    print("Output:")
    print("\t", (name1 == 'SHAI') and (name2 == 'SHAI'))
    print("---------------------------------------------------------")
    print("    ")


    email = 'adenosinetriphosphate@smail.com'
    password = 'ayosnaman'

    print("2. or : \n")
    print("Input:")
    print(f'\temail = "{email}"\n\tpassword = "{password}"')
    print("\tprint((email == 'adenosinetriphosphate@smail.com') or (password == 'hatdog'))")
    print("Output:")
    print("\t", (email == 'adenosinetriphosphate@smail.com') or (password == 'hatdog'))
    print("---------------------------------------------------------")
    print("    ")


    cc1 = 1      
    cc2 = 1 

    print("3. not : \n")
    print("Input:")
    print(f'\tcc1 = 1\n\tcc2 = 1')
    print("\tprint(not(cc1 == cc2))")
    print("Output:")
    print("\t", not(cc1 == cc2))
    print("---------------------------------------------------------")

def three_d():
    print("---------------------------------------------------------")
    print("---> Assignment operators are used to assign values to variables")
    print("\nTYPES OF ASSIGNMENT OPERATORS\n")
    print("  =        : assigns value to a variable                     -> x = 5")
    print("  +=       : adds and assigns                                -> x += 3  (x = x + 3)")
    print("  -=       : subtracts and assigns                           -> x -= 2  (x = x - 2)")
    print("  *=       : multiplies and assigns                          -> x *= 4  (x = x * 4)")
    print("  /=       : divides and assigns                             -> x /= 2  (x = x / 2)")
    print("  %=       : modulus and assigns                             -> x %= 3  (x = x % 3)")
    print("  **=      : exponentiation and assigns                      -> x **= 2 (x = x ** 2)")
    print("  //=      : floor division and assigns                      -> x //= 2 (x = x // 2)")
    print("---------------------------------------------------------")

    x = "rainraingoaway"
    y = 99
    print("1. = : \n")
    print("Input:")
    print('1. \n\tx = "rainraingoaway"')
    print("\tprint(x)")
    print("2. \n\ty = 99")
    print("\tprint(y)")
    print("Output:")
    print("\t", x)
    print("\t", y)
    print("---------------------------------------------------------")
    print("    ")
    x = 5
    x += 3
    print("2. += : \n")
    print("Input:")
    print("\tx = 5\n\tx += 3")
    print("\tprint(x)")
    print("Output:")
    print("\t", x)
    print("---------------------------------------------------------")
    print("    ")
    x = 10
    x -= 2
    print("3. -= : \n")
    print("Input:")
    print("\tx = 10\n\tx -= 2")
    print("\tprint(x)")
    print("Output:")
    print("\t", x)
    print("---------------------------------------------------------")
    print("    ")
    x = 4
    x *= 4
    print("4. *= : \n")
    print("Input:")
    print("\tx = 4\n\tx *= 4")
    print("\tprint(x)")
    print("Output:")
    print("\t", x)
    print("---------------------------------------------------------")
    print("    ")
    x = 20
    x /= 2
    print("5. /= : \n")
    print("Input:")
    print("\tx = 20\n\tx /= 2")
    print("\tprint(x)")
    print("Output:")
    print("\t", x)
    print("---------------------------------------------------------")
    print("    ")
    x = 10
    x %= 3
    print("6. %= : \n")
    print("Input:")
    print("\tx = 10\n\tx %= 3")
    print("\tprint(x)")
    print("Output:")
    print("\t", x)
    print("---------------------------------------------------------")
    print("    ")
    x = 5
    x **= 2
    print("7. **= : \n")
    print("Input:")
    print("\tx = 5\n\tx **= 2")
    print("\tprint(x)")
    print("Output:")
    print("\t", x)
    print("---------------------------------------------------------")
    print("    ")
    x = 17
    x //= 2
    print("8. //= : \n")
    print("Input:")
    print("\tx = 17\n\tx //= 2")
    print("\tprint(x)")
    print("Output:")
    print("\t", x)
    print("---------------------------------------------------------")

def four():
    print("-----------------------------------------------------------")
    print("---> Conditional statements in Python are used to make decisions\n based on whether a condition is True or False.")
    print("-----------------------------------------------------------")
    print("----------------------------------------------------")
    print("|            These are the subtopics of            |")
    print("|                 Conditional Statements           |")
    print("|                                                  |")
    print("|              a. if statement                     |")
    print("|              b. if-else statement                |")
    print("|              c. if-elif-else statement           |")
    print("|              d. Nested statements                |")
    print("----------------------------------------------------")

def four_a():
    print("---------------------------------------------------------")
    print("---> An if statement runs code only if its condition is True.")
    print("---------------------------------------------------------")
    print("Input:")
    print("1. \tx = 8")
    print("   \tif x > 5:")
    print("   \t    print('x is greater than 5')")
    print("2. \tage = 17")
    print("   \tif  == 17:")
    print("   \t    print('Good morning, minor!')")
    print("   ")
    print("Output: ")
    print("1. \tx is greater than 5")
    print("   ")
    print("2. \tGood morning, minor!")
    print("---------------------------------------------------------")
 

def four_b(): 
    print("---------------------------------------------------------")
    print("---> 'else' statement is executed when the \nif condition (and any elif conditions) evaluate to False.")
    print("---------------------------------------------------------")
    print("---> An if-else statement runs one block if the condition is True,")
    print("     and another block if the condition is False.")
    print("---------------------------------------------------------")
    print("Input:")
    print("1. \tx = 4")
    print("   \tif x > 5:")
    print("   \t    print('x is greater than 5')")
    print("   \telse:")
    print("   \t    print('x is not greater than 5')")
    print("2. \tname = 'Sam'")
    print("   \tage = 15")
    print("   \tif age >= 18:")
    print("   \t    print(f'Good day, {name}, you can now proceed.')")
    print("   \telse:")
    print("   \t    print(f'Hi {name}, minors cannot proceed.')")
    print("   ")
    print("Output: ")
    print("1. \tx is not greater than 5")
    print("   ")
    print("2. \tHi Sam, minors cannot proceed.")
    print("---------------------------------------------------------")

def four_c():
    print("---------------------------------------------------------")
    print("---> An if-elif-else statement checks multiple conditions.")
    print("   If the first condition is False, it moves to elif, and finally else.")
    print("---------------------------------------------------------")
    print("Input:")
    print("1. \tage = 18")
    print("   \tif age < 13:")
    print("   \t    print('Child')")
    print("   \telif age < 20:")
    print("   \t    print('Teenager')")
    print("   \telse:")
    print("   \t    print('Adult')")
    print("   ")
    print("Output: ")
    print("1. \tTeenager")
    print("---------------------------------------------------------")

def four_d():
    print("---------------------------------------------------------")
    print("---> Nested statements can use if, elif, and else inside another if.")
    print("     This allows multiple levels of conditions to be checked step by step.")
    print("---------------------------------------------------------")
    print("Input:")
    print("1. print('Hi, Welcome to Manga Recommender!')")
    print("   print('\\nAnswer a few questions to find your next read.')")
    print("   genre = 'action'")
    print("   duration = 'long'")
    print("   decade = '2000s'")
    print("             ")
    print("   if genre == 'action':")
    print("       if duration == 'long':")
    print("           if decade == '2000s':")
    print("               print('One Piece, Naruto, Bleach')")
    print("           else:")
    print("               print('Attack on Titan')")
    print("   elif genre == 'romance':")
    print("       if duration == 'short':")
    print("           print('Lovely★Complex')")
    print("       else:")
    print("           print('Kimi ni Todoke')")
    print("   else:")
    print("       print('Sorry, that genre is not available')")
    print("   ")
    print("Output:")
    print("1. Hi, Welcome to Manga Recommender!")
    print("   ")
    print("   One Piece, Naruto, Bleach")
    print("---------------------------------------------------------")

def five():
    print("-----------------------------------------------------------")
    print("---> Loops allow you to run a block of code repeatedly. They make it easier \nto handle repetitive tasks without writing the same code again and again.")
    print("-----------------------------------------------------------")
    print("----------------------------------------------------")
    print("|            These are the subtopics of            |")
    print("|                     Loops in Python              |")
    print("|                                                  |")
    print("|              a. for loop                         |")
    print("|              b. nested for loop                  |")
    print("|              c. while loop                       |")
    print("|              d. break and continue statements    |")
    print("----------------------------------------------------")


def five_a():
    print("---------------------------------------------------------")
    print("---> A for loop is a programming construct that allows a block of ")
    print("   code to be ran repeatedly until a certain condition is met.")
    print("\nCONDITIION: ")
    print("   - start: the number to begin with")
    print("   - stop: the number to end before")
    print("   - step: the step or skip between numbers")
    print("---------------------------------------------------------")
    print("Input:")
    print("1. \tfor num in range(0, 10, 2):")
    print("   \t    print(num)")
    print("   ")
    print("2. \tfor s in range(5):")
    print('   \t    print("sorry")')
    print("   ")
    

    print("Output: ")
    print("1. \t0")
    print("   \t2")
    print("   \t4")
    print("   \t6")
    print("   \t8")
    print("   ")
    print("2. \tsorry")
    print("   \tsorry")
    print("   \tsorry")
    print("   \tsorry")
    print("---------------------------------------------------------")

def five_b():
    print("---------------------------------------------------------")
    print("---> A nested for loop is a loop inside a loop.")
    print(' The "inner loop" will be executed one time for each iteration of the "outer loop"')
    print("\nCONDITIION: ")
    print("   - start: the number to begin with")
    print("   - stop: the number to end before")
    print("   - step: the step or skip between numbers")
    print("---------------------------------------------------------")
    print("---------------------------------------------------------")
    print("Input:")
    print("1. \tfor a in range(1, 9):")
    print("   \t    for b in range(9, a, -1):")
    print('   \t        print(" ", end=" ")')
    print("   \t    for b in range(2, a, 1):")
    print('   \t        print("*", end=" ")')
    print("   \t    for c in range(1, a, 1):")
    print('   \t        print("*", end=" ")')
    print("   \t    print()")
    print("   ")
    print("Output: ")
    print("1. \t                *")
    print("   \t              * * *")
    print("   \t            * * * * *")
    print("   \t          * * * * * * *")
    print("   \t        * * * * * * * * *")
    print("   \t      * * * * * * * * * * *")
    print("   \t    * * * * * * * * * * * * *")
    print("   \t  * * * * * * * * * * * * * * *")
    print("---------------------------------------------------------")

def five_c():
    print("---------------------------------------------------------")
    print("---> A while loop in Python literally keeps running")
    print("   as long as the condition given remains True.")
    print("---------------------------------------------------------")
    print("Input:")
    print("1. \tcount = 1") 
    print("   \twhile count < 6:")
    print("   \t    print(count)")
    print("   \t    count += 1")
    print("   ")
    print("Output: ")
    print("1. \t1")
    print("   \t2")
    print("   \t3")
    print("   \t4")
    print("   \t5")
    print("---------------------------------------------------------")

def five_d():
    print("---------------------------------------------------------")
    print("---> A while loop is a programming construct that allows a block of ")
    print("   code to be ran repeatedly until a certain condition is met.")
    print("\nCONDITION: ")
    print("break - used to exit the loop immediately")
    print("continue - used to skip the rest of the \ncode in the loop and go back to the condition check")
    print("---------------------------------------------------------")
    print("Input:")
    print("1.  while True:")
    print('      music = input("Do you want to continue listening to the playlist? (yes/no) --> ").lower()')
    print("      if music == 'yes':")
    print('          print("Playing the next song..\\n")')
    print("          continue")
    print("      elif music == 'no':")
    print('          print("I\'m stopping the music now..\\n")')
    print("          break")
    print("      else:")
    print('          print("Huh? Please answer the question properly\\n")')
    print("          continue")
    print("   ")
    print("Output:")
    print("1.   - Do you want to continue listening to the playlist? (yes/no) --> yes")
    print("     Playing the next song..")
    print("     - Do you want to continue listening to the playlist? (yes/no) --> no")
    print("     I'm stopping the music now..")
    print("    -  Do you want to continue listening to the playlist? (yes/no) --> maybe")
    print("     Huh? Please answer the question properly")
    print("-----------------------------------------------------------")

def six():
    print("-----------------------------------------------------------")
    print("---> A list in Python is a collection used to store multiple items in one variable \n allowing you to ")
    print("store, access, and manipulate collections of data easily.")
    print("-----------------------------------------------------------")
    print("----------------------------------------------------")
    print("|            These are the subtopics of            |")
    print("|                    Lists in Python               |")
    print("|                                                  |")
    print("|              a. Creating lists                   |")
    print("|              b. Accessing elements               |")
    print("|              c. List methods                     |")
    print("|              d. Iterating through lists          |")
    print("----------------------------------------------------")

def six_a():
    print("---------------------------------------------------------")
    print("---> Lists are written with square brackets [ ].")
    print("---------------------------------------------------------")
    print("Input:")
    print("1. \tmy_list = [1, 2, 3, 4, 5]")
    print("   \tprint(my_list)")
    print("   ")
    print("2. \tfruits = ['apple', 'banana', 'cherry']")
    print("   \tprint(fruits)")
    print("   ")
    print("Output:")
    print("1. \t[1, 2, 3, 4, 5]")
    print("   ")
    print("2. \t['apple', 'banana', 'cherry']")
    print("---------------------------------------------------------")

def six_b():
    print("---------------------------------------------------------")
    print("---> You can access elements in a list by using their index number.")
    print("   Indexing in Python starts at 0 (the first element).")
    print("---------------------------------------------------------")
    print("Input:")
    print("1. \tlugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']")
    print("   \tprint(lugar[0])   # first element")
    print("   \tprint(lugar[3])   # third element")
    print("   ")
    print("Output:")
    print("1. \tlucena")
    print("   \tatimonan")
    print("   ")
    print("---------------------------------------------------------")

def six_c():
    print("---------------------------------------------------------")
    print("---> List methods are built-in functions that allow you to")
    print(" add, remove, and manipulate items in a list easily.")
    print("\nCOMMON LIST METHODS\n")

    # append()
    lugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']
    lugar.append('tayabas')
    print("1. append() : \n")
    print("Input:")
    print("\tlugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']")
    print("\tlugar.append('tayabas')")
    print("\tprint(lugar)")
    print("Output:")
    print("\t", lugar)
    print("---------------------------------------------------------\n")

    # insert()
    lugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']
    lugar.insert(2, 'pagbilao')
    print("2. insert() : \n")
    print("Input:")
    print("\tlugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']")
    print("\tlugar.insert(2, 'pagbilao')")
    print("\tprint(lugar)")
    print("Output:")
    print("\t", lugar)
    print("---------------------------------------------------------\n")

    # remove()
    lugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']
    lugar.remove('mulanay')
    print("3. remove() : \n")
    print("Input:")
    print("\tlugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']")
    print("\tlugar.remove('mulanay')")
    print("\tprint(lugar)")
    print("Output:")
    print("\t", lugar)
    print("---------------------------------------------------------\n")

    # pop()
    lugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']
    lugar.pop()
    print("4. pop() : \n")
    print("Input:")
    print("\tlugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']")
    print("\tlugar.pop()")
    print("\tprint(lugar)")
    print("Output:")
    print("\t", lugar)
    print("---------------------------------------------------------\n")

    # sort()
    lugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']
    lugar.sort()
    print("5. sort() : \n")
    print("Input:")
    print("\tlugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']")
    print("\tlugar.sort()")
    print("\tprint(lugar)")
    print("Output:")
    print("\t", lugar)
    print("---------------------------------------------------------\n")

    # reverse()
    lugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']
    lugar.reverse()
    print("6. reverse() : \n")
    print("Input:")
    print("\tlugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']")
    print("\tlugar.reverse()")
    print("\tprint(lugar)")
    print("Output:")
    print("\t", lugar)
    print("---------------------------------------------------------\n")

    # clear()
    lugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']
    lugar.clear()
    print("7. clear() : \n")
    print("Input:")
    print("\tlugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']")
    print("\tlugar.clear()")
    print("\tprint(lugar)")
    print("Output:")
    print("\t", lugar)
    print("---------------------------------------------------------")


def six_d():
    print("---------------------------------------------------------")
    print("---> Iterating through a list means accessing each item")
    print("   one by one, usually with a loop like 'for'.")
    print("---------------------------------------------------------")
    print("Input:")
    print("1. \tlugar = ['lucena', 'sariaya', 'mulanay', 'atimonan']")
    print("   \tfor quezon in lugar:")
    print("   \t    print(quezon)")
    print("   ")
    print("Output:")
    print("1. \tlucena")
    print("   \tsariaya")
    print("   \tmulanay")
    print("   \tatimonan")
    print("   ")
    print("---------------------------------------------------------")

def seven():
    print("-----------------------------------------------------------")
    print("---> A function in Python is a reusable block of code that runs only when \ncalled, helping organize tasks and avoid repetition.")
    print("-----------------------------------------------------------")
    print("----------------------------------------------------")
    print("|            These are the subtopics of            |")
    print("|                  Functions in Python             |")
    print("|                                                  |")
    print("|              a. Defining functions               |")
    print("|              b. Calling a function               |")
    print("----------------------------------------------------")

def seven_a():
    print("-----------------------------------------------------------")
    print("---> A function is defined using the 'def' keyword,")
    print("   followed by a name and parentheses ().")
    print("-----------------------------------------------------------")
    print("Input:")
    print("1. \tdef greet():")
    print("   \t    print('Hello!')")
    print("   \t")
    print("Output:")
    print("1. \t")
    print("   ")
    print("-----------------------------------------------------------")

def seven_b():
    print("-----------------------------------------------------------")
    print("---> To call the function, write its name followed by parentheses")
    print("-----------------------------------------------------------")
    print("Input:")
    print("1. \tdef greet():")
    print("   \t    print('Hello!')")
    print("   \tgreet()")
    print("   ")
    print("   ")
    print("Output:")
    print("1. \tHello!")
    print("   ")
    print("-----------------------------------------------------------")



